### ISSUE TITLE
\subsubsection 不显示章节号的数字

### ISSUE THREAD

**Issue by JackWang1017** [latexstudio/CUMCMThesis#1]
正常情况下`\subsubsection{新的一章}`在文章里的结果应该是：
> 1.1.1 新的一章

`但是现在的模板中，'\subsubsection'的结果并没有前面的数字，就是：
> 新的一章

也就是说下面的这个代码没起到作用：
`\renewcommand\thesubsubsection{\thesubsection\thinspace.\thinspace\arabic{subsubsection}}`
这个问题在去年的模板里就已经存在了。

另外我现在的环境是TeXLive 2016，去年的环境是TeXLive 2015，我不知道CTEX下有没有问题，希望您有时间能够检查一下这个问题，感激不尽。

**Comment by latexstudio** [comment]
\setcounter{secnumdepth}{3}
加一个这个即可。



latexstudio@yeah.net
 
发件人： JackWang1017
发送时间： 2016-09-05 18:23
收件人： latexstudio/CUMCMThesis
主题： [latexstudio/CUMCMThesis] \subsubsection 不显示章节号的数字 (#1)
正常情况下\subsubsection{新的一章}在文章里的结果应该是：
1.1.1 新的一章
`但是现在的模板中，'\subsubsection'的结果并没有前面的数字，就是：
新的一章
也就是说下面的这个代码没起到作用：
\renewcommand\thesubsubsection{\thesubsection\thinspace.\thinspace\arabic{subsubsection}}
这个问题在去年的模板里就已经存在了。
另外我现在的环境是TeXLive 2016，去年的环境是TeXLive 2015，我不知道CTEX下有没有问题，希望您有时间能够检查一下这个问题，感激不尽。
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
--> -->
-->

**Comment by JackWang1017** [comment]
非常感谢！
